SpecialZoo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zoo/', include('zoo.urls','zoo')),
    path('tickets/', include('tickets.urls','ticket')),
    path('', include('user.urls','user'))
]

user/urls.py
# from django import views
from django.urls import path
from user.views import CreateRecord, ListRecord, UpdateRecord, DeleteRecord, Index, CreateRecordWithEmailConfirm, VerificationActivationCode
from django.contrib.auth.views import LogoutView
from . import views
from SpecialZoo import settings
app_name = 'user'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('iniciar-sesion/', views.login_page, name='login'),
    path('cerrar-sesion/', LogoutView.as_view(), name='logout'),
    path('activar_usuario/<str:uid>', VerificationActivationCode.as_view(), name='activate'),
    # path('cerrar-sesion/', views.logout, name='logout'),
    path('lista/', ListRecord.as_view(), name='list'),
    path('registro/', CreateRecordWithEmailConfirm.as_view(), name='signup'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete'),
    path('actualizar/<int:pk>', UpdateRecord.as_view(), name='update'),
]

zoo/urls.py
from django.urls import path
from zoo.views import CreateRecord, DeleteRecord, ListRecord, UpdateRecord, ViewRecord
app_name = 'zoo'

urlpatterns = [
    path('', ListRecord.as_view(), name='home'),
    path('detalle/<int:pk>', ViewRecord.as_view(), name='detail'),
    path('crear/', CreateRecord.as_view(), name='create'),
    path('editar/<int:pk>', UpdateRecord.as_view(), name='update'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete')
]

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  	<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block metas %} {% endblock %}
        
        <!-- Styles -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        {% block stylesheets %} {% endblock %}

        <!-- Head Scripts -->
        {% block headscripts %}{% endblock %}

        <!-- Title -->
        <title>Special Zoo - {% block title %} {% endblock %}</title>
    </head>
    <body class="{{request.resolver_match.url_name}} {% if request.user.is_authenticated %} auth{% else %} anon{% endif %}{% block body_classes %}{% endblock %}" {% block body_attrs %} {% endblock %}>
        <!-- <div>{{request|pprint}}</div> -->
        <div id="wrapper" class="position-relative min-h-screen">
            <header>
                {% include "menu.html" %}
            </header>
            <main id="main">
                <section id="layout-messages-wrapper">
                    {% block messages %}
                        {% if messages %}
                            <div class="container">
                                <div class="row align-items-center justify-content-center">            
                                    <div class="col-12">
                                        {% for message in messages %}
                                            <div class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}success{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% endif %} alert-dismissible fade show" role="alert">
                                                <p>{{message}}</p>
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endblock %}
                </section>
                <section id="content">
                    {% block content %}
                    {% endblock %}
                </section>
            </main>
            <footer class="footer position-absolute fixed-bottom">
                <div class="copyright text-center">
                    <p>
                        Todos los derechos reservados
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script> | <b>PROJECT NAME</b>
                    </p>
                </div>
            </footer>
        </div>
        
        <!-- Modals -->
        {% block modal %}

        {% endblock %}

        <!-- Scripts -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- <script src="{% static 'js/script.js' %}"></script> -->
        {% block scripts %}{% endblock %}
    </body>
</html>

templates/layouts/menu.html
{% load static %}
<nav id="menu" class="navbar navbar-light navbar-expand-lg">
    <div class="container">
            <a class="navbar-brand" href="{% if request.user.is_authenticated %} {% url 'zoo:home' %} {% else %} {% url 'zoo:home' %} {% endif %}">
                PROJECT
            </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-menu-navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse w-100" id="main-menu-navbar-collapse">
            <ul class="navbar-nav w-100 justify-content-center">	
                <li class="nav-item {% if request.resolver_match.view_name == 'zoo:home' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'zoo:home' %}">Inicio</a>
                </li>                  
                <li class="nav-item">
                    <a href="{% url 'user:list' %}" class="nav-link">lista</a>
                </li>
                <li class="nav-item">
                    <a href="{{request.META.HTTP_REFERER|escape}}" class="nav-link">Back</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'user:logout' %}" class="nav-link">Cerrar sesión</a>
                    </li>
                {% endif %}
            </ul>
      </div>
    </div>
</nav>