SpecialZoo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zoo/', include('zoo.urls','zoo')),
    path('tickets/', include('tickets.urls','ticket')),
    path('', include('user.urls','user'))
]

tickets/urls.py
from django.urls import path
from tickets.views import Index, CreateTicket
app_name = 'ticket'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('calendario/<int:pk>', CreateTicket.as_view(), name='calendar'),
    path('calendario/pago/<int:pk>', CreateTicket.as_view(), name='pay_info'),
]

user/urls.py
# from django import views
from django.urls import path
from user.views import CreateRecord, ListRecord, UpdateRecord, DeleteRecord, Index, CreateRecordWithEmailConfirm, VerificationActivationCode
from django.contrib.auth.views import LogoutView
from . import views
from SpecialZoo import settings
app_name = 'user'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('iniciar-sesion/', views.login_page, name='login'),
    path('cerrar-sesion/', LogoutView.as_view(), name='logout'),
    path('activar_usuario/<str:uid>', VerificationActivationCode.as_view(), name='activate'),
    # path('cerrar-sesion/', views.logout, name='logout'),
    path('lista/', ListRecord.as_view(), name='list'),
    path('registro/', CreateRecordWithEmailConfirm.as_view(), name='signup'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete'),
    path('actualizar/<int:pk>', UpdateRecord.as_view(), name='update'),
]

zoo/urls.py
from django.urls import path
from zoo.views import CreateRecord, DeleteRecord, ListRecord, UpdateRecord, ViewRecord
app_name = 'zoo'

urlpatterns = [
    path('', ListRecord.as_view(), name='home'),
    path('detalle/<int:pk>', ViewRecord.as_view(), name='detail'),
    path('crear/', CreateRecord.as_view(), name='create'),
    path('editar/<int:pk>', UpdateRecord.as_view(), name='update'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete')
]

tickets/models.py
from django.db import models
from zones.models import Zone

class TicketType(models.Model):
    name = models.CharField(max_length=30)
    img_url = models.FileField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'ticket_types'

class ZoneTicketType(models.Model):
    id_ticket_type = models.ForeignKey(TicketType, on_delete=models.SET_NULL, null=True)
    id_zone = models.ForeignKey(Zone, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'zone_ticket_types'

class Ticket(models.Model):
    id_ticket_type = models.ForeignKey(TicketType, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    entrance_value = models.FloatField()
    reserved_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
        
    class Meta:
        db_table = 'tickets'

tickets/forms.py
from django import forms

class CalendarForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'disabled':'disabled',
                'value':'Pase normal'
            }), label='Nombre del pase')
    value = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control',
                'value':5.99
            }), label='Precio')
    reserved_date = forms.DateTimeField(
        widget=forms.DateInput(
            attrs={
                'class':'form-control', 
                'type':'date'
            }), label='Día reservado')

class PayInfoForm(forms.Form):
    card_num = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}), label='Numero de tarjeta')
    exp_date = forms.DateTimeField(widget=forms.DateInput(attrs={'class':'form-control','type':'date'}), label='Fecha de Expiración')
    CVC = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control', 'max':'9999'}), label='CVC')

tickets/views.py
from email.policy import default
import pdb
from pprint import pprint
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, UpdateView
from tickets.forms import CalendarForm, PayInfoForm
from zones.models import Zone
from tickets.models import Ticket, TicketType
from django.http import JsonResponse
import json

class Index(ListView):
    queryset = TicketType.objects.order_by('created_at')
    template_name = 'ticket/index.html'
    context_object_name = 'records'

    # Validate user
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'GET':
                return super().dispatch(request, *args, **kwargs)
            elif request.method == 'POST':
                # pdb.set_trace()
                return JsonResponse(json.loads(request.body.decode('utf-8')))
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

class CreateTicket(FormView):
    template_name = 'ticket/ticket_step01.html'
    context_object_name = 'form'
    form_class = CalendarForm
    
    # Validates
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'GET':
                return super().dispatch(request, *args, **kwargs)
            elif request.method == 'POST':
                zona = Zone.objects.get(id=self.kwargs.get('pk'))
                ticket = Ticket.objects.create(name='Pase para '+zona.name)
                ticket.zones.set([zona], through_defaults={'reserved_date': request.POST['reserved_date'], 'value':request.POST['value']})
                request.session['ticket_in_buy_process'] = ticket
                return redirect('ticket:pay_info')
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

class UpdateTicket(UpdateView):
    template_name = 'ticket/ticket_step02.html'
    context_object_name = 'form'
    form_class = PayInfoForm
    
    # Validates
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Validacion del tiquete
            ticket = request.session.get('ticket_in_buy_process', None)
            if ticket is None:
                return redirect('ticket:index')
            
            # Validar metodos
            if request.method == 'GET':
                return super().dispatch(request, *args, **kwargs)
            elif request.method == 'POST':
                if request.POST['card_num'].isnumeric() and request.POST['CVC'].isnumeric():
                    # TODO: Actualizar el ticket
                    redirect('ticket:index')
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

templates/ticket/form.html
<div class="crud-form-fields-wrapper">
    <div class="row">
        {% for field in form %}
            <div class="col-12 mb-3">
                <label for="id_{{field.name}}" class="form-label">{{field.label}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <div class="col-12 crud-submit-button-wrapper d-flex justify-content-between">
            <a class="btn btn-secondary" href="{% url 'ticket:index' %}">Volver</a>
            <button type="submit" class="btn btn-primary">Continuar</button>
        </div>
    </div>
</div>

templates/ticket/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Tipos de Pases {% endblock %}
{% block scripts %}
    <script src="{% static 'js/tickets.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container pb-5">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-12">
                            <h1>Seleccion de las entradas</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-3">
                            <h2>Escoja la fecha deseada:</h2>
                            <input class="form-control" type="date" name="reserved_date" id="reserved_date">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h2>Escoja el tipo deseado:</h2>
                            {% if records.all.count > 0 %}
                                {% for record in records %}
                                <div class="card d-inline-block" style="width: 320px;">
                                    <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" style="height: 420px; width: 100%; display: block;" src={{ record.img_url }} data-holder-rendered="true">
                                    <div class="card-body">
                                      <h5 class="card-title">{{ record.name }}</h5>
                                      <button tt_id="{{ record.id }}" class="btn btn-primary add_button col-12">Add</button>
                                    </div>
                                </div>
                                {% endfor %}
                                {% csrf_token %}
                            {% else %}
                                <p colspan="9" style="text-align: center;">No hay entradas</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 p-5 d-flex justify-content-between">
                    <a class="btn btn-secondary" href="{% url 'user:index' %}">Volver</a>
                    <a class="btn btn-primary" href="">Seguir</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ticket/ticket_step01.html
{% extends "base.html" %}

{% block title %} Comprar pase {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Seleccion de las entradas</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h2>Escoja la fecha deseada:</h2>
                            <input class="form-control" type="date" name="reserved_date" id="reserved_date">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h2>Escoja el tipo deseado:</h2>
                            {% if form and form is not None %}
                                <form method="post">
                                    {% csrf_token %}
                                    {% include "ticket/form.html" %}
                                </form>
                            {% else %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ticket/ticket_step02.html
{% extends "base.html" %}

{% block title %} Selección de la fecha {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Elección de la fecha</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form method="post">
                                    {% csrf_token %}
                                    {% include "ticket/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en la creación del registro, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}