SpecialZoo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zoo/', include('zoo.urls','zoo')),
    path('tickets/', include('tickets.urls','ticket')),
    path('', include('user.urls','user'))
]

zoo/urls.py
from django.urls import path
from zoo.views import CreateRecord, DeleteRecord, ListRecord, UpdateRecord, ViewRecord
app_name = 'zoo'

urlpatterns = [
    path('', ListRecord.as_view(), name='home'),
    path('detalle/<int:pk>', ViewRecord.as_view(), name='detail'),
    path('crear/', CreateRecord.as_view(), name='create'),
    path('editar/<int:pk>', UpdateRecord.as_view(), name='update'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete')
]

zoo/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from animal_size.models import AnimalSize

class Animal(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.CharField(max_length=255, blank=False, null=False)
    gender = models.CharField(max_length=6, blank=False, null=False)
    size = models.ForeignKey(AnimalSize, to_field='name', on_delete=models.SET_NULL, null=True, blank=True)
    life_span = models.PositiveIntegerField(blank=False, null=False, validators=[MinValueValidator(1), MaxValueValidator(150)])
    type_of_bird = models.CharField(max_length=80, blank=False, null=False)
    family = models.CharField(max_length=255, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'animal'

zoo/forms.py
from django import forms
from zoo.models import Animal

class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        exclude = ['type_of_bird']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['size'].widget.attrs.update({'class': "form-control form-select"})
        self.fields['size'].empty_label = 'Escoja un tamaño'
        self.fields['life_span'].widget.attrs.update({'class': 'form-control', 'max':'150', 'min':'1'})
        self.fields['family'].widget.attrs.update({'class': 'form-control'})

zoo/views.py
import pdb
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from zoo.forms import AnimalForm
from zoo.models import Animal

class ListRecord(ListView):
    queryset = Animal.objects.order_by('created_at')
    template_name = 'zoo/home.html'
    context_object_name = 'records'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AnimalForm
    
        return context
        
class CreateRecord(CreateView):
    template_name = 'zoo/create.html'
    context_object_name = 'form'
    form_class = AnimalForm
    success_url = reverse_lazy('zoo:home')

    def form_valid(self, form):
        messages.success(self.request, 'Se guardo un animal correctamente')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Los datos proporcionados son invalidos")
        return redirect('zoo:home')

class ViewRecord(DetailView):
    template_name = 'zoo/detail.html'
    model = Animal
    context_object_name = 'record'

class UpdateRecord(UpdateView):
    template_name = 'zoo/update.html'
    model = Animal
    form_class = AnimalForm
    context_object_name = 'form'
    success_url = reverse_lazy('zoo:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['record_id'] = self.kwargs.get('pk')

        return context

    def form_valid(self, form):
        messages.success(self.request, "Actualizado correctamente")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.errro(self.request, "Error al actualizar")
        return redirect('zoo:update')

class DeleteRecord(DeleteView):
    model = Animal
    success_url = reverse_lazy('zoo:home')

templates/zoo/create.html
{% extends "base.html" %}

{% block title %} Agregar nuevo animal al zoologico {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Nuevo animal</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form action="{% url 'zoo:create' %}" method="post">
                                    {% csrf_token %}
                                    {% include "zoo/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en la creación del registro, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/zoo/delete_modal.html
<div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Eliminar Pato</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              ¿Estás seguro que deseas eliminar {% if object is not None %} a {{object.name}} 
              {% else %}
              este animal
              {% endif %}?
          </div>
          <div class="modal-footer">
              <form method="post" id="form-delete">
                  {% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                  <button type="submit" id="btn-delete-confirmation" class="btn btn-danger">Eliminar</button>
              </form>
          </div>
      </div>
  </div>
</div>

templates/zoo/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} Detalle de animal {% endblock %}
{% block scripts %}
    <script src="{% static 'js/crud.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="https://via.placeholder.com/286x180" alt="Card image cap">
                                <div class="card-body">
                                    <h5 class="card-title">{{object.name}}</h5>
                                    <p class="card-text">{{object.description}}</p>
                                    <p class="card-text">{{object.family}}</p>
                                    <p class="card-text">{{object.life_span}}</p>
                                    <div class="btn-group col-12" role="group">
                                        <a class="btn btn-outline-success" href="{% url 'zoo:update' record.id  %}">Editar</a>
                                        <button type="button" data-record-del-url="{% url 'zoo:delete' record.id  %}" class="btn btn-outline-danger record-delete">Borrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "zoo/delete_modal.html" %}
{% endblock %}

templates/zoo/form.html
<div class="crud-form-fields-wrapper">
    <div class="row">
        {% for field in form %}
            <div class="col-12 mb-3">
                <label for="id_{{field.name}}" class="form-label">{{field.label}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <div class="col-12 crud-submit-button-wrapper">
            <input type="submit" class="btn btn-primary"
                    value="Guardar">
            {% if record_id %}
                <a class="btn btn-secondary" href="{% url 'zoo:detail' record_id %}">volver</a>
            {% endif %}
        </div>
    </div>
</div>

templates/zoo/home.html
{% extends "base.html" %}
{% load static %}
{% block title %} Special Zoo {% endblock %}
{% block scripts %}
    <script src="{% static 'js/crud.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <h2>este el contenido de zoo</h2>
        <div class="row">
            <div class="col-2">
                <a class="btn btn-outline-dark mb-3" href="{% url 'zoo:create' %}">Nuevo animal</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-dark table-hover text-center">
                    <thead>
                        <tr>
                          <th scope="col">ID</th>
                          <th scope="col">Nombre</th>
                          <th scope="col">Descripción</th>
                          <th scope="col">Esperanza de vida</th>
                          <th scope="col">Familia</th>
                          <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if records.all.count > 0 %}
                            {% for record in records %}
                                <tr>
                                    <th scope="row">{{record.id}}</th>
                                    <td>{{record.name}}</td>
                                    <td>{{record.description}}</td>
                                    <td>{{record.life_span}}</td>
                                    <td>{{record.family}}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-outline-primary" href="{% url 'zoo:detail' record.id  %}">Ver</a>
                                            <button type="button" data-record-del-url="{% url 'zoo:delete' record.id  %}" class="btn btn-outline-danger record-delete">Borrar</button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            {% include "zoo/delete_modal.html" %}
                        {% else %}
                            <tr><td colspan="9" style="text-align: center;">No hay animales</td></tr>
                        {% endif %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/zoo/update.html
{% extends "base.html" %}

{% block title %} Actualizar {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Actualizando a {{ object.name }}</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form method="post">
                                    {% csrf_token %}
                                    {% include "zoo/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en la creación del registro, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}