SpecialZoo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zoo/', include('zoo.urls','zoo')),
    path('tickets/', include('tickets.urls','ticket')),
    path('', include('user.urls','user'))
]

user/urls.py
# from django import views
from django.urls import path
from user.views import CreateRecord, ListRecord, UpdateRecord, DeleteRecord, Index, CreateRecordWithEmailConfirm, VerificationActivationCode
from django.contrib.auth.views import LogoutView
from . import views
from SpecialZoo import settings
app_name = 'user'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('iniciar-sesion/', views.login_page, name='login'),
    path('cerrar-sesion/', LogoutView.as_view(), name='logout'),
    path('activar_usuario/<str:uid>', VerificationActivationCode.as_view(), name='activate'),
    # path('cerrar-sesion/', views.logout, name='logout'),
    path('lista/', ListRecord.as_view(), name='list'),
    path('registro/', CreateRecordWithEmailConfirm.as_view(), name='signup'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete'),
    path('actualizar/<int:pk>', UpdateRecord.as_view(), name='update'),
]

zoo/urls.py
from django.urls import path
from zoo.views import CreateRecord, DeleteRecord, ListRecord, UpdateRecord, ViewRecord
app_name = 'zoo'

urlpatterns = [
    path('', ListRecord.as_view(), name='home'),
    path('detalle/<int:pk>', ViewRecord.as_view(), name='detail'),
    path('crear/', CreateRecord.as_view(), name='create'),
    path('editar/<int:pk>', UpdateRecord.as_view(), name='update'),
    path('eliminar/<int:pk>', DeleteRecord.as_view(), name='delete')
]

user/models.py
import email
from statistics import mode
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    user_active_url_code = models.CharField(default='', max_length=60)
    user_active_code = models.CharField(default='', max_length=6)

    # A string describing the name of the field on the user model that is used as the unique identifier.
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    objects = BaseUserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perm(self, app_label):
        return True

# https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#substituting-a-custom-user-model

user/forms.py
from dataclasses import fields
from django import forms
from .models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Correo')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Contraseña')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','username','password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].label = 'Correo'
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].label = 'Nombre de usuario'
        self.fields['password'] = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Contraseña')
        self.fields['conf_password'] = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='Repita la contraseña')

class UserFormUpdate(UserChangeForm):
    class Meta:
        model = User
        fields = ['email','username','is_admin','is_active','is_staff']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].label = 'Correo'
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].label = 'Nombre de usuario'
        self.fields['is_admin'].widget.attrs.update({'class': "form-check-input"})
        self.fields['is_active'].widget.attrs.update({'class': "form-check-input"})
        self.fields['is_staff'].widget.attrs.update({'class': "form-check-input"})

# class RegistrationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ('email','username','password1','password2')

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['email'].widget.attrs.update({'class': 'form-control'})
#         self.fields['email'].label = 'Correo'
#         self.fields['username'].widget.attrs.update({'class': 'form-control'})
#         self.fields['username'].label = 'Nombre de usuario'
#         self.fields['password1'].widget.attrs.update({'class': 'form-control'})
#         self.fields['password2'].widget.attrs.update({'class': 'form-control'})

user/views.py
import pdb
from pprint import pprint
from random import randint
from tkinter import NO
from turtle import pd
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from user.forms import UserForm, UserFormUpdate, LoginForm
from user.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.core.mail import EmailMessage
from django.conf import settings

# TODO: Reordenar todo
class ListRecord(ListView):
    queryset = User.objects.order_by('date_joined')
    template_name = 'user/list.html'
    context_object_name = 'records'

    # Validate user
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'GET':
                return super().dispatch(request, *args, **kwargs)
            elif request.method == 'POST':
                messages.error(request, 'Acción invalida.')
                return redirect('user:login')    
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserForm
    
        return context

class CreateRecord(CreateView):
    template_name = 'user/sign_up.html'
    context_object_name = 'form'
    form_class = UserForm
    # form_class = RegistrationForm
    success_url = reverse_lazy('zoo:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = False
        
        return context

    def form_valid(self, form):
        password = self.request.POST.get('password', None)
        conf_password = self.request.POST.get('conf_password', None)
        if password and conf_password:
            if password == conf_password:
                # email = self.request.POST.get('email', None)
                # user_session = authenticate(email=email, password=password)
                # form.cleaned_data['user_code'] = get_random_string(length=60)
                # pdb.set_trace()
                user_instance = form.save()
                login(self.request, user_instance)
                messages.success(self.request, 'Registro exitoso')
                # return user_instance
                return super().form_valid(form)
        return super().form_invalid(form)

    def form_invalid(self, form):
        # pdb.set_trace()
        messages.error(self.request, "Los datos proporcionados son invalidos")
        return redirect('user:signup')

class UpdateRecord(UpdateView):
    template_name = 'user/update.html'
    model = User
    form_class = UserFormUpdate
    context_object_name = 'form'
    success_url = reverse_lazy('user:list')

    # Validate user
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # pdb.set_trace()
            if request.user.is_admin or request.user.id == self.kwargs.get('pk'):
                return super().dispatch(request, *args, **kwargs)
            else:
                messages.error(request, 'No estas autorizado.')
                return redirect('user:index')    
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = True
        
        return context

    def form_valid(self, form):
        messages.success(self.request, "Actualizado correctamente")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.errro(self.request, "Error al actualizar")
        return redirect('user:update')

class DeleteRecord(DeleteView):
    model = User
    success_url = reverse_lazy('user:list') 
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_admin:
                return super().dispatch(request, *args, **kwargs)
            else:
                messages.error(request, 'No estas autorizado.')
                return redirect('user:index')
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

# TODO: revisar por que no funciona correctamente
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'Sesión Cerrada')
        return redirect('user:login')

def login_page(request):
    form = LoginForm()
    message = ''
    context = {'form': form, 'message': message}
    # Validate user
    if request.user.is_authenticated:
        return redirect('user:index')
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                user = authenticate(
                    username = form.cleaned_data['email'],
                    password = form.cleaned_data['password'],
                )
                # pdb.set_trace()
                if user is not None:
                    login(request, user)
                    return redirect('user:index')
                message = 'Login failed!'
        return render(request, 'user/login.html', context)

class Index(TemplateView):
    template_name = 'user/index.html'

    # Validate user
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'GET':
                return super().dispatch(request, *args, **kwargs)
            elif request.method == 'POST':
                messages.error(request, 'Acción invalida. ¡Inicia Sesión!')
                return redirect('user:index')    
        else:
            messages.error(request, 'Por favor inicia sesión e intenta de nuevo.')
            return redirect('user:login')

# ====================================================================================
class VerificationActivationCode(TemplateView):
    template_name = 'user/activation_account.html'
    # pdb.set_trace()
    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            try:
                user = User.objects.get(user_active_url_code=self.kwargs.get('uid'))
            except Exception as e: 
                user = None
            
            if user is None:
                messages.error(self.request, 'El usuario con ese codigo no existe')
                
            return super().dispatch(request, *args, **kwargs)

        if request.method == 'POST':
            try:
                user = User.objects.get(user_active_url_code=self.kwargs.get('uid'))
            except Exception as e:
                user = None
            
            if user:
                if request.POST['active_code'] == user.user_active_code:
                    user.is_active = True
                    user.user_active_code = ''
                    user.user_active_url_code = ''
                    user.save()
                    return redirect('user:login')
                else:
                    messages.error(self.request, 'Codigo invalido, por favor asegurate de que sea correcto')
                    return redirect(request.path)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_valid_user'] = True

        try:
            user = User.objects.get(user_active_url_code=self.kwargs.get('uid'))
        except Exception as e: 
            user = None

        if user is None:
            context['is_valid_user'] = False
        
        return context

def send_activation_email(user, request):
    current_site = get_current_site(request)
    email_subject = "Activate your account"
    email_body = render_to_string('user/acc_active_email.html', {
        'user': user,
        'domain': current_site,
        'uid': user.user_active_url_code,
    })

    email_message = EmailMessage(subject=email_subject, body=email_body, from_email=settings.EMAIL_HOST_USER, to=[user.email])
    email_message.content_subtype = "html"
    email_message.send(fail_silently=False)

class CreateRecordWithEmailConfirm(CreateView):
    template_name = 'user/sign_up.html'
    context_object_name = 'form'
    form_class = UserForm
    success_url = reverse_lazy('zoo:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_update'] = False
        
        return context

    def form_valid(self, form):
        password = self.request.POST.get('password', None)
        conf_password = self.request.POST.get('conf_password', None)
        if password and conf_password:
            if password == conf_password:
                user_instance = form.save()
                setattr(user_instance,'user_active_url_code',get_random_string(length=60))
                setattr(user_instance,'user_active_code',randint(100000, 999999))
                user_instance.save()
                send_activation_email(user_instance, self.request)
                
                if not user_instance.is_active:
                    messages.error(self.request, 'Por favor revisa tu correo para activar tu cuenta')
                    return redirect('user:login')


                login(self.request, user_instance)
                messages.success(self.request, 'Registro exitoso')
                return super().form_valid(form)
        return super().form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Los datos proporcionados son invalidos")

templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Este es tu codigo de activación <strong>{{user.user_active_code}}</strong>
Por favor, <a href="http://{{ domain }}{% url 'user:activate' uid=uid %}"> haz click aquí </a>  para continuar con tu registro.
{% endautoescape %}

templates/user/activation_account.html
{% extends "base.html" %}

{% block title %} Activar usuario {% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-4">
                <h1 class="h3 mb-3">Digita tu codigo de activación</h1>
                {% if is_valid_user %}
                    <form method="post" class="text-align-center">
                        {% csrf_token %}
                        <input type="number" class="form-control" name="active_code" id="active_code">
                        <button class="btn btn-primary mt-3 col-4" type="submit">Enviar</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
<!-- TODO: terminar los estilos -->

templates/user/activation_failed.html
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Ha ocurrido un error al momento de confirmar tu cuenta</h1>
        </div>
    </div>
</div>

templates/user/delete_modal.html
<div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Eliminar Usuario</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              ¿Estás seguro que deseas eliminar {% if object is not None %} a {{object.name}} 
              {% else %}
              este usuario
              {% endif %}?
          </div>
          <div class="modal-footer">
              <form method="post" id="form-delete">
                  {% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                  <button type="submit" id="btn-delete-confirmation" class="btn btn-danger">Eliminar</button>
              </form>
          </div>
      </div>
  </div>
</div>

templates/user/form.html
<div class="crud-form-fields-wrapper">
    <div class="row">
        {% for field in form %}
            {% if is_update %}
                {% if field.name != "password" or field.name != "conf-password" %}
                    <div class="col-12 mb-3">
                        <label for="id_{{field.name}}" class="form-label">{{field.label}}</label>
                        {{ field }}
                    </div>
                {% endif %}
            {% else %}
                <div class="col-12 mb-3">
                    <label for="id_{{field.name}}" class="form-label">{{field.label}}</label>
                    {{ field }}
                </div>
            {% endif %}
        {% endfor %}
        <div class="col-12 crud-submit-button-wrapper">
            <input type="submit" class="btn btn-primary"
                    value="Guardar">
            {% if record_id %}
                <a class="btn btn-secondary" href="{% url 'user:list' record_id %}">volver</a>
            {% endif %}
        </div>
    </div>
</div>

templates/user/index.html
{% extends "base.html" %}

{% block title %} Inicio del usuario {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6">
                    <div class="row">
                        <h1>Home</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Usuarios {% endblock %}
{% block scripts %}
    <script src="{% static 'js/crud.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Lista de usuarios del zoo</h2>
        <div class="row">
            <div class="col-2">
                <a class="btn btn-outline-dark mb-3" href="{% url 'user:signup' %}">Registrar nuevo usuario</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-dark table-hover text-center">
                    <thead>
                        <tr>
                          <th scope="col">ID</th>
                          <th scope="col">Nombre de usuario</th>
                          <th scope="col">Correo</th>
                          <th scope="col">Estado</th>
                          <th scope="col">Ultima vez</th>
                          <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if records.all.count > 0 %}
                            {% for record in records %}
                                <tr>
                                    <th scope="row">{{record.id}}</th>
                                    <td>{{record.username}}</td>
                                    <td>{{record.email}}</td>
                                    {% if record.is_active %}
                                        <td>activo</td>
                                    {% else %}
                                        <td>inactivo</td>
                                    {% endif %}
                                    <td>{{record.last_login}}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Botones de Acciones">
                                            <a class="btn btn-outline-primary" href="{% url 'user:update' record.id  %}">Editar</a>
                                            <button type="button" data-record-del-url="{% url 'user:delete' record.id  %}" class="btn btn-outline-danger record-delete">Borrar</button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            {% include "user/delete_modal.html" %}
                        {% else %}
                            <tr><td colspan="9" style="text-align: center;">No hay usuarios</td></tr>
                        {% endif %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %} Registro usuario {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Iniciar Sesión</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form action="{# url 'user:login' #}" method="post">
                                    {% csrf_token %}
                                    {% include "user/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en el inicio de sesión, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/sign_up.html
{% extends "base.html" %}

{% block title %} Registro usuario {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Nuevo usuario</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form action="{# url 'user:create' #}" method="post">
                                    {% csrf_token %}
                                    {% include "user/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en la creación del registro, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/update.html
{% extends "base.html" %}

{% block title %} Actualizar {% endblock %}

{% block content %}
    <div id="regions-create-wrapper" class="template-content-wrapper">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6" id="crud-form-card-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <h1>Actualizando a {{ object.username }}</h1>
                        </div>
                        <div class="col-12" id="crud-form-wrapper">
                            {% if form and form is not None %}
                                <form method="post">
                                    {% csrf_token %}
                                    {% include "user/form.html" %}
                                </form>
                            {% else %}
                                <div class="p-5 mb-4 bg-dark rounded-3">
                                    <h2 class="text-center text-white">
                                        Ha ocurrido un error en la creación del registro, por favor inténtelo mas tarde.
                                    </h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}